default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --force-exclude
        language: system
        files: \.pyi?$
        stages:
          - pre-commit
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --check --force-exclude
        language: system
        files: \.pyi?$
        stages:
          - pre-commit
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        stages:
          - pre-push
