repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --force-exclude
        language: system
        files: \.pyi?$
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --check --force-exclude
        language: system
        files: \.pyi?$
