[project]
name = "imsim"
version = "0.1.0"
description = "Inventory Management Simulator (Dash)"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "dash>=3.2.0",
    "dash-bootstrap-components>=2.0.4",
    "dash-bootstrap-templates>=2.1.0",
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "numpy>=2.2.6",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "plotly>=6.3.0",
]